### ISSUE TITLE
请教一下这个数据库是怎么建的啊 我这边一直server error 500

### ISSUE THREAD

**Issue by lxyhahalxy** [Feng-Yz/Study-Helper#7]

**Comment by yuzhenfeng2002** [comment]
您可能需要购买一个服务器（以CentOS为例）并在上面配置MySQL。再在控制台修改防火墙的设置、开放用于MySQL的3306端口。

接着：

在本地使用SSH远程登陆：
```bash
ssh root@xxx.xxx.xxx.xxx -p 22
```

下载并安装MySQL的源安装包：
```bash
wget http://dev.mysql.com/get/mysql57-community-release-el7-10.noarch.rpm
yum localinstall mysql57-community-release-el7-10.noarch.rpm
```

禁用CentOS自带的MySQL模块：
```bash
yum module disable mysql
```

安装MySQL：
```bash
yum install mysql-community-server
```

启动并设置开机启动：
```bash
systemctl start mysqld
systemctl enable mysqld
systemctl daemon-reload
```

获取默认密码：
```bash
grep "password" /var/log/mysqld.log
```

复制该密码后登陆MySQL进行修改：
```bash
mysql -uroot -p
```

```mysql
SET PASSWORD FOR 'root'@'localhost'=password('new password');
```

可创建一个新用户并授权：
```mysql
CREATE USER 'WebProject2021'@'%' IDENTIFIED BY 'password';
GRANT CREATE, DELETE, UPDATE, SELECT ON WebProject.* TO 'WebProject2021'@'%';
```

设置MySQL的默认编码：
```bash
vim /etc/my.cnf

character_set_server=utf8
init_connect='SET NAMES utf8'

systemctl restart mysqld
```

接着要在`ai_study_helper/settings.py`文件中修改Line78-86的配置。包括数据库名、用户名、密码、公有IP、端口号。

**Comment by lxyhahalxy** [comment]
能看一下您数据库建的表吗 我这里能注册和登录后显示table don't exit



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月12日(周五) 晚上7:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Feng-Yz/Django-Web-of-Study-Helper] 请教一下这个数据库是怎么建的啊 我这边一直server error 500 (Issue #7)




 
您可能需要购买一个服务器（以CentOS为例）并在上面配置MySQL。再在控制台修改防火墙的设置、开放用于MySQL的3306端口。
 
接着：
 
在本地使用SSH远程登陆：
 ssh ***@***.*** -p 22
 
下载并安装MySQL的源安装包：
 wget http://dev.mysql.com/get/mysql57-community-release-el7-10.noarch.rpm yum localinstall mysql57-community-release-el7-10.noarch.rpm
 
禁用CentOS自带的MySQL模块：
 yum module disable mysql
 
安装MySQL：
 yum install mysql-community-server
 
启动并设置开机启动：
 systemctl start mysqld systemctl enable mysqld systemctl daemon-reload
 
获取默认密码：
 grep "password" /var/log/mysqld.log
 
复制该密码后登陆MySQL进行修改：
 mysql -uroot -p
 SET PASSWORD FOR 'root'@'localhost'=password('new password');
 
可创建一个新用户并授权：
 CREATE USER 'WebProject2021'@'%' IDENTIFIED BY 'password'; GRANT CREATE, DELETE, UPDATE, SELECT ON WebProject.* TO 'WebProject2021'@'%';
 
设置MySQL的默认编码：
 vim /etc/my.cnf character_set_server=utf8 init_connect='SET NAMES utf8' systemctl restart mysqld
 
接着要在ai_study_helper/settings.py文件中修改Line78-86的配置。包括数据库名、用户名、密码、公有IP、端口号。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yuzhenfeng2002** [comment]
Django会自动建表。
<img width="250" alt="截屏2021-11-12 19 42 34" src="https://user-images.githubusercontent.com/61533778/141461734-6cf72772-c3dd-49ff-8f0f-8b9280ea8b54.png">

**Comment by lxyhahalxy** [comment]
我的只自动建了前十个没有后面helper的表



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月12日(周五) 晚上7:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Feng-Yz/Django-Web-of-Study-Helper] 请教一下这个数据库是怎么建的啊 我这边一直server error 500 (Issue #7)




 
您可能需要购买一个服务器（以CentOS为例）并在上面配置MySQL。再在控制台修改防火墙的设置、开放用于MySQL的3306端口。
 
接着：
 
在本地使用SSH远程登陆：
 ssh ***@***.*** -p 22
 
下载并安装MySQL的源安装包：
 wget http://dev.mysql.com/get/mysql57-community-release-el7-10.noarch.rpm yum localinstall mysql57-community-release-el7-10.noarch.rpm
 
禁用CentOS自带的MySQL模块：
 yum module disable mysql
 
安装MySQL：
 yum install mysql-community-server
 
启动并设置开机启动：
 systemctl start mysqld systemctl enable mysqld systemctl daemon-reload
 
获取默认密码：
 grep "password" /var/log/mysqld.log
 
复制该密码后登陆MySQL进行修改：
 mysql -uroot -p
 SET PASSWORD FOR 'root'@'localhost'=password('new password');
 
可创建一个新用户并授权：
 CREATE USER 'WebProject2021'@'%' IDENTIFIED BY 'password'; GRANT CREATE, DELETE, UPDATE, SELECT ON WebProject.* TO 'WebProject2021'@'%';
 
设置MySQL的默认编码：
 vim /etc/my.cnf character_set_server=utf8 init_connect='SET NAMES utf8' systemctl restart mysqld
 
接着要在ai_study_helper/settings.py文件中修改Line78-86的配置。包括数据库名、用户名、密码、公有IP、端口号。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yuzhenfeng2002** [comment]
那您可以尝试一下依次运行
```bash
python manage.py makemigrations
python manage.py migrate
```
